services:
  - type: web
    name: youtube-downloader-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
